# Generated by Django 4.1.2 on 2022-11-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='record',
            table='records',
        ),
    ]
