# Generated by Django 4.1.3 on 2022-11-14 04:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0003_record_audio_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='record',
            table=None,
        ),
    ]
