# Generated by Django 4.0.2 on 2022-11-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0004_alter_record_options_alter_record_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
