# Generated by Django 4.0.2 on 2022-11-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stt', '0005_alter_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.IntegerField(db_column='id', editable=False, primary_key=True, serialize=False),
        ),
    ]
